### ISSUE TITLE
Phenotypes-genes: Need parsing of gene IDs from these files

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/phenoCompare#20]
@hannahblau Github doesn't support csv files (but it does support XLSX (?!)).  Anyways, instead of converting them, I just uploaded the folder to google docs.
I'd like the gene names and Entrez Ids to be in separate columns.
Thanks

https://drive.google.com/drive/folders/1JgjZCzfrqVwnpKm7vmQkpBgeG08lKm0T?usp=sharing

**Comment by hannahblau** [comment]
[https://drive.google.com/drive/folders/12Dm_huUP--EymkFf3_me9gTZthNGT8af?usp=sharing](https://drive.google.com/drive/folders/12Dm_huUP--EymkFf3_me9gTZthNGT8af?usp=sharing)

You will find two types of files in this folder: HPOterm_T.csv and HPOterm_GENES.csv. The _T file has all the fields of the source file HPOterm.csv, but the gene name and gene id have been separated into two columns and the file is sorted by gene name. I also stripped out the header and footer lines. The _GENES file contains only the gene names, one per line.
